import datetime

class PresentationGenerator:
    def __init__(self):
        self.template = """
# Executive Summary: {topic}

**Date:** {date}
**Generated by:** AI Research Agent

---

## 📊 Overview

{overview}

## 🔑 Key Findings

{key_findings}

## 🚀 Recent Developments

{recent_developments}

## ⚠️ Challenges & Limitations

{challenges}

## 🔮 Future Outlook

{future_outlook}

## 📚 Sources

{sources}

---

*This presentation was automatically generated by AI research agent.*
"""
    
    def generate_presentation(self, research_data, topic):
        """Generate structured presentation from research data"""
        
        # Format each section
        overview = self._generate_overview(research_data, topic)
        key_findings = self._format_list(research_data.get('key_points', []))
        recent_developments = self._format_list(research_data.get('recent_developments', []))
        challenges = self._format_list(research_data.get('challenges', []))
        future_outlook = self._format_list(research_data.get('future_outlook', []))
        sources = self._format_sources(research_data.get('sources', []))
        
        # Fill template
        presentation = self.template.format(
            topic=topic,
            date=datetime.datetime.now().strftime("%Y-%m-%d"),
            overview=overview,
            key_findings=key_findings,
            recent_developments=recent_developments,
            challenges=challenges,
            future_outlook=future_outlook,
            sources=sources
        )
        
        return presentation
    
    def _generate_overview(self, research_data, topic):
        """Generate executive overview"""
        total_points = len(research_data.get('key_points', []))
        total_sources = len(research_data.get('sources', []))
        
        overview = f"""
This research provides a comprehensive analysis of **{topic}**, synthesizing information from {total_sources} authoritative sources. The analysis covers key technological advancements, current challenges, and future projections in this rapidly evolving field.

**Research Scope:** 
- Analyzed {total_points} key insights
- Identified major trends and developments
- Assessed current limitations and opportunities
- Projected future directions

"""
        return overview.strip()
    
    def _format_list(self, items):
        """Format list items with markdown"""
        if not items:
            return "* No specific information identified in research"
        
        formatted = ""
        for i, item in enumerate(items[:5], 1):  # Top 5 items
            formatted += f"{i}. {item}\n"
        
        return formatted
    
    def _format_sources(self, sources):
        """Format sources list"""
        if not sources:
            return "* Research sources not available"
        
        formatted = ""
        for i, source in enumerate(sources[:3], 1):  # Top 3 sources
            formatted += f"{i}. {source}\n"
        
        return formatted